version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: starbuck
      MYSQL_USER: adminton
      MYSQL_PASSWORD: test123
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
